var yytranslate_table_ =
[
  //]
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
   158,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,   157,   144,     2,     2,     2,   142,   137,     2,
   153,   154,   140,   138,   151,   139,   150,   141,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,   132,   156,
   134,   130,   133,   131,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,   149,     2,   155,   136,     2,   152,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,   147,   135,   148,   145,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
    15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
    25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
    65,    66,    67,    68,    69,    70,    71,    72,    73,    74,
    75,    76,    77,    78,    79,    80,    81,    82,    83,    84,
    85,    86,    87,    88,    89,    90,    91,    92,    93,    94,
    95,    96,    97,    98,    99,   100,   101,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   111,   112,   113,   114,
   115,   116,   117,   118,   119,   120,   121,   122,   123,   124,
   125,   126,   127,   128,   129,   143,   146
  //[
];

var yytname_ =
[
  //]
  "\"end-of-input\"", "error", "$undefined", "keyword_class",
"keyword_module", "keyword_def", "keyword_undef", "keyword_begin",
"keyword_rescue", "keyword_ensure", "keyword_end", "keyword_if",
"keyword_unless", "keyword_then", "keyword_elsif", "keyword_else",
"keyword_case", "keyword_when", "keyword_while", "keyword_until",
"keyword_for", "keyword_break", "keyword_next", "keyword_redo",
"keyword_retry", "keyword_in", "keyword_do", "keyword_do_cond",
"keyword_do_block", "keyword_do_LAMBDA", "keyword_return",
"keyword_yield", "keyword_super", "keyword_self", "keyword_nil",
"keyword_true", "keyword_false", "keyword_and", "keyword_or",
"keyword_not", "modifier_if", "modifier_unless", "modifier_while",
"modifier_until", "modifier_rescue", "keyword_alias", "keyword_defined",
"keyword_BEGIN", "keyword_END", "keyword__LINE__", "keyword__FILE__",
"keyword__ENCODING__", "tIDENTIFIER", "tFID", "tGVAR", "tIVAR",
"tCONSTANT", "tCVAR", "tLABEL", "tINTEGER", "tFLOAT", "tSTRING_CONTENT",
"tCHAR", "tNTH_REF", "tBACK_REF", "tREGEXP_END", "tUPLUS", "\"unary+\"",
"tUMINUS", "\"unary-\"", "tPOW", "\"**\"", "tCMP", "\"<=>\"", "tEQ",
"\"==\"", "tEQQ", "\"===\"", "tNEQ", "\"!=\"", "tGEQ", "\">=\"", "tLEQ",
"\"<=\"", "\"&&\"", "\"||\"", "tMATCH", "\"=~\"", "tNMATCH", "\"!~\"",
"tDOT2", "\"..\"", "tDOT3", "\"...\"", "tAREF", "\"[]\"", "tASET",
"\"[]=\"", "tLSHFT", "\"<<\"", "tRSHFT", "\">>\"", "\"::\"",
"\":: at EXPR_BEG\"", "tOP_ASGN", "\"=>\"", "\"(\"", "\"( arg\"",
"\")\"", "\"[\"", "\"{\"", "\"{ arg\"", "\"*\"", "\"**arg\"", "\"&\"",
"\"->\"", "tSYMBEG", "tSTRING_BEG", "tXSTRING_BEG", "tREGEXP_BEG",
"tWORDS_BEG", "tQWORDS_BEG", "tSYMBOLS_BEG", "tQSYMBOLS_BEG",
"tSTRING_DBEG", "tSTRING_DEND", "tSTRING_DVAR", "tSTRING_END", "tLAMBEG",
"tLOWEST", "'='", "'?'", "':'", "'>'", "'<'", "'|'", "'^'", "'&'", "'+'",
"'-'", "'*'", "'/'", "'%'", "tUMINUS_NUM", "'!'", "'~'", "tLAST_TOKEN",
"'{'", "'}'", "'['", "'.'", "','", "'`'", "'('", "')'", "']'", "';'",
"' '", "'\\n'", "$accept", "program", "$@1", "top_compstmt", "top_stmts",
"top_stmt", "$@2", "bodystmt", "compstmt", "stmts", "stmt_or_begin",
"$@3", "stmt", "$@4", "command_asgn", "expr", "expr_value",
"command_call", "block_command", "cmd_brace_block", "@5", "fcall",
"command", "mlhs", "mlhs_inner", "mlhs_basic", "mlhs_item", "mlhs_head",
"mlhs_post", "mlhs_node", "lhs", "cname", "cpath", "fname", "fsym",
"fitem", "undef_list", "$@6", "op", "reswords", "arg", "$@7",
"arg_value", "aref_args", "paren_args", "opt_paren_args",
"opt_call_args", "call_args", "command_args", "@8", "block_arg",
"opt_block_arg", "args", "mrhs", "primary", "@9", "$@10", "$@11", "$@12",
"$@13", "$@14", "$@15", "$@16", "$@17", "$@18", "@19", "@20", "@21",
"@22", "@23", "$@24", "$@25", "primary_value", "k_begin", "k_if",
"k_unless", "k_while", "k_until", "k_case", "k_for", "k_class",
"k_module", "k_def", "k_end", "then", "do", "if_tail", "opt_else",
"for_var", "f_marg", "f_marg_list", "f_margs", "block_args_tail",
"opt_block_args_tail", "block_param", "opt_block_param",
"block_param_def", "opt_bv_decl", "bv_decls", "bvar", "lambda", "@26",
"@27", "f_larglist", "lambda_body", "do_block", "@28", "block_call",
"method_call", "@29", "@30", "@31", "@32", "brace_block", "@33", "@34",
"case_body", "cases", "opt_rescue", "exc_list", "exc_var", "opt_ensure",
"literal", "strings", "string", "string1", "xstring", "regexp", "words",
"word_list", "word", "symbols", "symbol_list", "qwords", "qsymbols",
"qword_list", "qsym_list", "string_contents", "xstring_contents",
"regexp_contents", "string_content", "@35", "@36", "@37", "@38",
"string_dvar", "symbol", "sym", "dsym", "numeric", "user_variable",
"keyword_variable", "var_ref", "var_lhs", "backref", "superclass",
"$@39", "f_arglist", "args_tail", "opt_args_tail", "f_args", "f_bad_arg",
"f_norm_arg", "f_arg_item", "f_arg", "f_kw", "f_block_kw",
"f_block_kwarg", "f_kwarg", "kwrest_mark", "f_kwrest", "f_opt",
"f_block_opt", "f_block_optarg", "f_optarg", "restarg_mark",
"f_rest_arg", "blkarg_mark", "f_block_arg", "opt_f_block_arg",
"singleton", "$@40", "assoc_list", "assocs", "assoc", "operation",
"operation2", "operation3", "dot_or_colon", "opt_terms", "opt_nl",
"rparen", "rbracket", "trailer", "term", "terms", "none", null
  //[
];